name: Manually publish documentation

on: workflow_dispatch

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm install
      - name: Build library
        run: npm run build
      - name: Build docs
        run: npm run build:doc
      - name: Deploy docs to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'origin-osaas-client-jsdocs'
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'dist/docs/osc-client-javascript-3.0.0/'
